spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:order_service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
#  instance:
#    hostname: ms.net
#    prefer-ip-address: false

  #sping cloud bus with kafka
#  cloud:
#    bus:
#      enabled: true
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: microsoft-service
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#  zipkin:
#    base-url: http://localhost:9411/zipkin

#  sleuth:
#    otel:
#      exporter:
#        jaeger:
#          endpoint: http://localhost:14268/api/traces
#          enabled: true
#    sampler:
#      probability: 1.0

#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh

  #Zipkin
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0

#logging:
#  config: ./share-resource/logback-spring.xml





