spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
  main:
    web-application-type: reactive
server:
  port: 8081
logging:
  level:
    root: INFO
